[tool.ruff]
line-length = 140
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
ignore = ["E731"]

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true

[tool.mypy]
strict = true
ignore_missing_imports = true
disable_error_code = ["misc", "no-untyped-call", "attr-defined", "union-attr", "call-overload"]





